platform :ios, '8.0'

# 去掉烦人的警告
inhibit_all_warnings!

target 'TZCarShare' do

pod 'MJRefresh'
pod 'SDWebImage'
pod 'SDWebImage/GIF'
pod 'MBProgressHUD+WJExtension', '~> 1.3.1'
pod 'AFNetworking', '~> 2.5.0'
pod 'FLExtension' , '~> 0.0.2'
pod 'MMDrawerController', '~> 0.5.7'

end
